pick_and_place:
  ros__parameters:
    grasp_pose:
      x: 0.4
      y: -0.3
      z: 0.2
      roll: 180.0   # degrees
      pitch: 0.0
      yaw: 0.0
    place_pose:
      x: 0.4
      y: 0.3
      z: 0.2
      roll: 180.0   # degrees
      pitch: 0.0
      yaw: 0.0
    approach_distance: 0.2  # metres
    eef_step: 0.01
    jump_threshold: 0.0
    min_fraction: 0.9
